### ISSUE TITLE
PyQt5 ERror

### ISSUE THREAD

**Issue by BionicLMAO11** [ProgrammingHero1/my_cool_browser#10]
it says this *Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2021.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.1.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/User/Hamdan/file.py", line 4, in <module>
    from PyQt5.QtWebEngineWidgets import *
  File "C:\Program Files\JetBrains\PyCharm 2021.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'**

**Comment by yashu208** [comment]
Same problem

**Comment by Prince2347X** [comment]
@yashu208 @BionicLMAO11 
Install it by running

```
pip install PyQtWebEngine
```
It's also mentioned in the video
