### ISSUE TITLE
QtWeb error

### ISSUE THREAD

**Issue by Develepor-Coder** [ProgrammingHero1/my_cool_browser#13]
line 4, in <module>
    from PyQt5.QtWebEngineWidgets import *
ImportError: DLL load failed while importing QtWebEngineWidgets: The specified module could not be found.

**Comment by hg0428** [comment]
```
Traceback (most recent call last) :
  File "main.py", line 4, in <module>
       from PyQtWebEngine import *
  ModuleNotFoundError: No module named 'PyQtWebEngine'
```

**Comment by ekansh-jaiswal** [comment]
> ```
> Traceback (most recent call last) :
>   File "main.py", line 4, in <module>
>        from PyQtWebEngine import *
>   ModuleNotFoundError: No module named 'PyQtWebEngine'
> ```

Just type 

pip install PyQtWebEngine

in the command prompt it shall work

**Comment by hg0428** [comment]
> > ```
> 
> > Traceback (most recent call last) :
> 
> >   File "main.py", line 4, in <module>
> 
> >        from PyQtWebEngine import *
> 
> >   ModuleNotFoundError: No module named 'PyQtWebEngine'
> 
> > ```
> 
> 
> 
> Just type 
> 
> 
> 
> pip install PyQtWebEngine
> 
> 
> 
> in the command prompt it shall work

Yea, you would think so, but nope, it still doesn't work.
I've moved on from QT and now I'm building a web engine from scratch to use in future projects.
